-- ============================================
-- CRIAÇÃO DAS TABELAS PRINCIPAIS
-- Execute no SQL Editor do seu Supabase
-- ============================================

-- Tabela de categorias
CREATE TABLE IF NOT EXISTS categorias (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(255) NOT NULL,
  slug VARCHAR(255) NOT NULL,
  cor VARCHAR(7) DEFAULT '#6366f1',
  descricao TEXT,
  imagem_url TEXT,
  ativo BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Tabela de compositores
CREATE TABLE IF NOT EXISTS compositores (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(255) NOT NULL,
  nome_artistico VARCHAR(255),
  biografia TEXT,
  avatar_url TEXT,
  verificado BOOLEAN DEFAULT false,
  ativo BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Tabela de hinos
CREATE TABLE IF NOT EXISTS hinos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  numero INTEGER NOT NULL,
  titulo VARCHAR(255) NOT NULL,
  compositor VARCHAR(255),
  categoria VARCHAR(100),
  cover_url TEXT,
  audio_url TEXT,
  duracao VARCHAR(10),
  ativo BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Tabela de albuns
CREATE TABLE IF NOT EXISTS albuns (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  titulo VARCHAR(255) NOT NULL,
  cover_url TEXT,
  compositor_id BIGINT REFERENCES compositores(id),
  ativo BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Tabela de banners
CREATE TABLE IF NOT EXISTS banners (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  image_url TEXT,
  link_type VARCHAR(50),
  link_url TEXT,
  link_id VARCHAR(255),
  gradient_overlay VARCHAR(20),
  is_active BOOLEAN DEFAULT true,
  position INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Habilitar RLS
ALTER TABLE categorias ENABLE ROW LEVEL SECURITY;
ALTER TABLE compositores ENABLE ROW LEVEL SECURITY;
ALTER TABLE hinos ENABLE ROW LEVEL SECURITY;
ALTER TABLE albuns ENABLE ROW LEVEL SECURITY;
ALTER TABLE banners ENABLE ROW LEVEL SECURITY;

-- Políticas públicas (para leitura)
CREATE POLICY "Enable read access for all users" ON categorias FOR SELECT USING (true);
CREATE POLICY "Enable read access for all users" ON compositores FOR SELECT USING (true);
CREATE POLICY "Enable read access for all users" ON hinos FOR SELECT USING (true);
CREATE POLICY "Enable read access for all users" ON albuns FOR SELECT USING (true);
CREATE POLICY "Enable read access for all users" ON banners FOR SELECT USING (true);
