-- Limpar views que possam estar usando o mesmo nome para evitar conflitos de relação
DROP VIEW IF EXISTS compositores;

-- Tabela de compositores
CREATE TABLE IF NOT EXISTS compositores (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Garantir colunas para compositores
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'compositores' AND column_name = 'user_id') THEN
        ALTER TABLE compositores ADD COLUMN user_id BIGINT REFERENCES usuarios(id) ON DELETE CASCADE;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'compositores' AND column_name = 'nome') THEN
        ALTER TABLE compositores ADD COLUMN nome VARCHAR(255) NOT NULL DEFAULT '';
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'compositores' AND column_name = 'nome_artistico') THEN
        ALTER TABLE compositores ADD COLUMN nome_artistico VARCHAR(255);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'compositores' AND column_name = 'biografia') THEN
        ALTER TABLE compositores ADD COLUMN biografia TEXT;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'compositores' AND column_name = 'telefone') THEN
        ALTER TABLE compositores ADD COLUMN telefone VARCHAR(20);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'compositores' AND column_name = 'verificado') THEN
        ALTER TABLE compositores ADD COLUMN verificado BOOLEAN DEFAULT false;
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'compositores' AND column_name = 'ativo') THEN
        ALTER TABLE compositores ADD COLUMN ativo BOOLEAN DEFAULT true;
    END IF;
END $$;
CREATE TABLE IF NOT EXISTS notifications (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Garantir que as colunas existam (Migration segura)
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'notifications' AND column_name = 'composer_id') THEN
        -- Alterado para referenciar usuarios, já que compositores não é uma tabela independente
        ALTER TABLE notifications ADD COLUMN composer_id BIGINT REFERENCES usuarios(id) ON DELETE CASCADE;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'notifications' AND column_name = 'type') THEN
        ALTER TABLE notifications ADD COLUMN type VARCHAR(50) NOT NULL DEFAULT 'admin';
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'notifications' AND column_name = 'title') THEN
        ALTER TABLE notifications ADD COLUMN title VARCHAR(255) NOT NULL DEFAULT '';
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'notifications' AND column_name = 'message') THEN
        ALTER TABLE notifications ADD COLUMN message TEXT;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'notifications' AND column_name = 'trigger_user_id') THEN
        ALTER TABLE notifications ADD COLUMN trigger_user_id BIGINT REFERENCES usuarios(id) ON DELETE SET NULL;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'notifications' AND column_name = 'song_id') THEN
        ALTER TABLE notifications ADD COLUMN song_id UUID REFERENCES hinos(id) ON DELETE SET NULL;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'notifications' AND column_name = 'album_id') THEN
        -- Alterado para referenciar 'albums' (inglês) conforme usado no supabase-api.ts
        -- Se a tabela não existir, o usuário receberá erro, mas assumimos que 'albums' é o correto.
        ALTER TABLE notifications ADD COLUMN album_id UUID REFERENCES albums(id) ON DELETE SET NULL;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'notifications' AND column_name = 'is_read') THEN
        ALTER TABLE notifications ADD COLUMN is_read BOOLEAN DEFAULT false;
    END IF;
END $$;


-- RLS para Notificações
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Composers can view their own notifications" ON notifications;
CREATE POLICY "Composers can view their own notifications" ON notifications
  FOR SELECT USING (auth.uid() IN (
    SELECT auth_id FROM usuarios WHERE id = notifications.composer_id
  ));

-- 2. Tabela de Reports (Denúncias)
CREATE TABLE IF NOT EXISTS reports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Garantir colunas para reports
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'reports' AND column_name = 'type') THEN
        ALTER TABLE reports ADD COLUMN type VARCHAR(50) NOT NULL DEFAULT 'other';
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'reports' AND column_name = 'title') THEN
        ALTER TABLE reports ADD COLUMN title VARCHAR(255) NOT NULL DEFAULT '';
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'reports' AND column_name = 'reporter_id') THEN
        ALTER TABLE reports ADD COLUMN reporter_id BIGINT REFERENCES usuarios(id) ON DELETE SET NULL;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'reports' AND column_name = 'reason') THEN
        ALTER TABLE reports ADD COLUMN reason TEXT NOT NULL DEFAULT '';
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'reports' AND column_name = 'status') THEN
        ALTER TABLE reports ADD COLUMN status VARCHAR(20) DEFAULT 'open';
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'reports' AND column_name = 'priority') THEN
        ALTER TABLE reports ADD COLUMN priority VARCHAR(20) DEFAULT 'medium';
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'reports' AND column_name = 'description') THEN
        ALTER TABLE reports ADD COLUMN description TEXT;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'reports' AND column_name = 'target_song_id') THEN
        ALTER TABLE reports ADD COLUMN target_song_id UUID REFERENCES hinos(id) ON DELETE SET NULL;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'reports' AND column_name = 'target_user_id') THEN
        ALTER TABLE reports ADD COLUMN target_user_id BIGINT REFERENCES usuarios(id) ON DELETE SET NULL;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'reports' AND column_name = 'resolved_at') THEN
        ALTER TABLE reports ADD COLUMN resolved_at TIMESTAMPTZ;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'reports' AND column_name = 'resolved_by') THEN
        ALTER TABLE reports ADD COLUMN resolved_by BIGINT REFERENCES usuarios(id);
    END IF;
END $$;


-- RLS para Reports
ALTER TABLE reports ENABLE ROW LEVEL SECURITY;

-- Admins podem ver tudo (supondo claim 'admin' ou tabela de usuarios com flag is_admin)
-- CREATE POLICY "Admins can view all reports" ON reports FOR ALL USING (
--   EXISTS (SELECT 1 FROM usuarios WHERE auth_id = auth.uid() AND tipo = 'admin')
-- );
-- Por enquanto, permitir leitura pública para facilitar o dev se RLS estiver on
DROP POLICY IF EXISTS "Enable read access for all users" ON reports;
CREATE POLICY "Enable read access for all users" ON reports FOR SELECT USING (true);

DROP POLICY IF EXISTS "Enable insert access for all users" ON reports;
CREATE POLICY "Enable insert access for all users" ON reports FOR INSERT WITH CHECK (true);

-- 3. View para Admin Stats (Opcional, mas útil)
-- Drop se existir para recriar
DROP VIEW IF EXISTS admin_stats_view;

CREATE OR REPLACE VIEW admin_stats_view AS
SELECT
  (SELECT count(*) FROM usuarios WHERE tipo = 'usuario') as total_users,
  (SELECT count(*) FROM usuarios WHERE tipo = 'compositor') as total_composers,
  (SELECT count(*) FROM hinos) as total_songs,
  (SELECT COALESCE(SUM(plays_count), 0) FROM hinos) as total_plays, -- assumindo coluna plays_count
  (SELECT count(*) FROM hinos WHERE ativo = true) as published_songs,
  (SELECT count(*) FROM reports WHERE status = 'open') as open_reports;
