-- ============================================================================
-- MODULO: Biblia Online - texto completo por traducao, livro, capitulo e verso
-- Projeto: Canticos CCB
--
-- Como usar:
--   1. Revise este arquivo.
--   2. Execute-o no SQL Editor do Supabase.
--   3. Importe os versiculos com service_role ou pelo SQL Editor.
--   4. Publique a traducao somente depois de validar todas as contagens.
--
-- A migracao e idempotente: pode ser executada novamente com seguranca.
-- ============================================================================

BEGIN;

-- --------------------------------------------------------------------------
-- Helper administrativo usado pelas politicas RLS do projeto.
-- --------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.is_admin_user()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT COALESCE(
    (SELECT u.is_admin FROM public.users AS u WHERE u.id = auth.uid()),
    false
  );
$$;

REVOKE ALL ON FUNCTION public.is_admin_user() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.is_admin_user() TO authenticated;

-- --------------------------------------------------------------------------
-- Traducao / edicao editorial.
-- --------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.bible_translations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code varchar(24) NOT NULL,
  name varchar(160) NOT NULL,
  short_name varchar(80) NOT NULL,
  language_code varchar(12) NOT NULL DEFAULT 'pt-BR',
  description text,
  copyright_holder text,
  rights_status varchar(40) NOT NULL DEFAULT 'pending_review',
  rights_basis text,
  license_name text,
  license_url text,
  attribution text,
  source_name text,
  source_url text,
  source_file_name text,
  editorial_notes text,
  is_active boolean NOT NULL DEFAULT true,
  is_published boolean NOT NULL DEFAULT false,
  published_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT bible_translations_code_unique UNIQUE (code),
  CONSTRAINT bible_translations_code_format CHECK (code = lower(code) AND code ~ '^[a-z0-9_-]+$'),
  CONSTRAINT bible_translations_rights_status_check CHECK (
    rights_status IN ('pending_review', 'user_declared_authorized', 'licensed', 'public_domain', 'open_license')
  ),
  CONSTRAINT bible_translations_publish_date_check CHECK (
    (is_published = false) OR (published_at IS NOT NULL)
  )
);

COMMENT ON TABLE public.bible_translations IS
  'Traducoes biblicas e seus dados editoriais, de origem, atribuicao e licenca.';

-- --------------------------------------------------------------------------
-- Livros. Cada traducao possui seu proprio catalogo para permitir futuras
-- traducoes sem alterar as URLs ou misturar textos.
-- --------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.bible_books (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  translation_id bigint NOT NULL REFERENCES public.bible_translations(id) ON DELETE CASCADE,
  canon_order smallint NOT NULL,
  testament varchar(24) NOT NULL,
  name varchar(100) NOT NULL,
  slug varchar(120) NOT NULL,
  abbreviation varchar(12) NOT NULL,
  chapters_count smallint NOT NULL,
  description text,
  is_published boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT bible_books_translation_order_unique UNIQUE (translation_id, canon_order),
  CONSTRAINT bible_books_translation_slug_unique UNIQUE (translation_id, slug),
  CONSTRAINT bible_books_testament_check CHECK (testament IN ('old', 'new')),
  CONSTRAINT bible_books_order_check CHECK (canon_order BETWEEN 1 AND 66),
  CONSTRAINT bible_books_chapters_check CHECK (chapters_count BETWEEN 1 AND 150),
  CONSTRAINT bible_books_slug_format CHECK (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$')
);

COMMENT ON TABLE public.bible_books IS
  'Catalogo canonico dos 66 livros para cada traducao.';

-- --------------------------------------------------------------------------
-- Capitulos. O slug permite URLs como 1-a-criacao-do-mundo.
-- --------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.bible_chapters (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  book_id bigint NOT NULL REFERENCES public.bible_books(id) ON DELETE CASCADE,
  chapter_number smallint NOT NULL,
  title varchar(220),
  slug varchar(260) NOT NULL,
  summary text,
  verses_count smallint NOT NULL DEFAULT 0,
  is_published boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT bible_chapters_book_number_unique UNIQUE (book_id, chapter_number),
  CONSTRAINT bible_chapters_book_slug_unique UNIQUE (book_id, slug),
  CONSTRAINT bible_chapters_number_check CHECK (chapter_number BETWEEN 1 AND 150),
  CONSTRAINT bible_chapters_verses_count_check CHECK (verses_count >= 0),
  CONSTRAINT bible_chapters_slug_format CHECK (slug ~ '^[0-9]+(?:-[a-z0-9]+)*$')
);

COMMENT ON TABLE public.bible_chapters IS
  'Metadados e estado editorial de cada capitulo.';

-- --------------------------------------------------------------------------
-- Versiculos. section_title e paragraph_number sustentam leitura editorial,
-- enquanto is_red_letter preserva as palavras de Jesus em vermelho.
-- --------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.bible_verses (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  chapter_id bigint NOT NULL REFERENCES public.bible_chapters(id) ON DELETE CASCADE,
  verse_number smallint NOT NULL,
  verse_text text NOT NULL,
  is_red_letter boolean NOT NULL DEFAULT false,
  paragraph_number smallint,
  section_title varchar(240),
  source_reference varchar(40),
  source_page integer,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  search_vector tsvector GENERATED ALWAYS AS (
    to_tsvector('portuguese', COALESCE(verse_text, ''))
  ) STORED,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT bible_verses_chapter_number_unique UNIQUE (chapter_id, verse_number),
  CONSTRAINT bible_verses_number_check CHECK (verse_number BETWEEN 1 AND 200),
  CONSTRAINT bible_verses_text_not_blank CHECK (length(btrim(verse_text)) > 0),
  CONSTRAINT bible_verses_paragraph_check CHECK (paragraph_number IS NULL OR paragraph_number >= 1),
  CONSTRAINT bible_verses_source_page_check CHECK (source_page IS NULL OR source_page >= 1)
);

COMMENT ON TABLE public.bible_verses IS
  'Texto de cada versiculo, com metadados de paragrafo, secao e palavras de Jesus.';

-- --------------------------------------------------------------------------
-- Auditoria de importacoes. Nao e exposta publicamente.
-- --------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.bible_imports (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  translation_id bigint NOT NULL REFERENCES public.bible_translations(id) ON DELETE CASCADE,
  source_file_name text NOT NULL,
  source_sha256 varchar(64),
  status varchar(24) NOT NULL DEFAULT 'pending',
  books_count integer NOT NULL DEFAULT 0,
  chapters_count integer NOT NULL DEFAULT 0,
  verses_count integer NOT NULL DEFAULT 0,
  invalid_rows_count integer NOT NULL DEFAULT 0,
  declared_rights_basis text,
  validation_report jsonb NOT NULL DEFAULT '{}'::jsonb,
  notes text,
  imported_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  started_at timestamptz NOT NULL DEFAULT now(),
  completed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT bible_imports_status_check CHECK (status IN ('pending', 'processing', 'validated', 'failed', 'published')),
  CONSTRAINT bible_imports_sha256_format CHECK (source_sha256 IS NULL OR source_sha256 ~ '^[a-f0-9]{64}$')
);

COMMENT ON TABLE public.bible_imports IS
  'Rastreabilidade do arquivo-fonte, contagens e validacoes de cada importacao.';

-- --------------------------------------------------------------------------
-- Indices para leitura, navegacao e busca.
-- --------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS bible_translations_public_idx
  ON public.bible_translations (is_active, is_published, code);

CREATE INDEX IF NOT EXISTS bible_books_navigation_idx
  ON public.bible_books (translation_id, canon_order, is_published);

CREATE INDEX IF NOT EXISTS bible_chapters_navigation_idx
  ON public.bible_chapters (book_id, chapter_number, is_published);

CREATE INDEX IF NOT EXISTS bible_verses_reader_idx
  ON public.bible_verses (chapter_id, verse_number);

CREATE INDEX IF NOT EXISTS bible_verses_search_idx
  ON public.bible_verses USING gin (search_vector);

CREATE INDEX IF NOT EXISTS bible_verses_red_letter_idx
  ON public.bible_verses (chapter_id, is_red_letter)
  WHERE is_red_letter = true;

CREATE INDEX IF NOT EXISTS bible_imports_translation_idx
  ON public.bible_imports (translation_id, created_at DESC);

-- --------------------------------------------------------------------------
-- updated_at automatico.
-- --------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.set_bible_updated_at()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS bible_translations_set_updated_at ON public.bible_translations;
CREATE TRIGGER bible_translations_set_updated_at
BEFORE UPDATE ON public.bible_translations
FOR EACH ROW EXECUTE FUNCTION public.set_bible_updated_at();

DROP TRIGGER IF EXISTS bible_books_set_updated_at ON public.bible_books;
CREATE TRIGGER bible_books_set_updated_at
BEFORE UPDATE ON public.bible_books
FOR EACH ROW EXECUTE FUNCTION public.set_bible_updated_at();

DROP TRIGGER IF EXISTS bible_chapters_set_updated_at ON public.bible_chapters;
CREATE TRIGGER bible_chapters_set_updated_at
BEFORE UPDATE ON public.bible_chapters
FOR EACH ROW EXECUTE FUNCTION public.set_bible_updated_at();

DROP TRIGGER IF EXISTS bible_verses_set_updated_at ON public.bible_verses;
CREATE TRIGGER bible_verses_set_updated_at
BEFORE UPDATE ON public.bible_verses
FOR EACH ROW EXECUTE FUNCTION public.set_bible_updated_at();

DROP TRIGGER IF EXISTS bible_imports_set_updated_at ON public.bible_imports;
CREATE TRIGGER bible_imports_set_updated_at
BEFORE UPDATE ON public.bible_imports
FOR EACH ROW EXECUTE FUNCTION public.set_bible_updated_at();

-- Mantem verses_count sincronizado sem depender do importador.
CREATE OR REPLACE FUNCTION public.refresh_bible_chapter_verses_count()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  affected_chapter_id bigint;
BEGIN
  IF TG_OP = 'DELETE' THEN
    affected_chapter_id := OLD.chapter_id;
  ELSE
    affected_chapter_id := NEW.chapter_id;
  END IF;

  UPDATE public.bible_chapters AS c
     SET verses_count = (
       SELECT count(*)::smallint
       FROM public.bible_verses AS v
       WHERE v.chapter_id = affected_chapter_id
     )
   WHERE c.id = affected_chapter_id;

  IF TG_OP = 'UPDATE' AND OLD.chapter_id IS DISTINCT FROM NEW.chapter_id THEN
    UPDATE public.bible_chapters AS c
       SET verses_count = (
         SELECT count(*)::smallint
         FROM public.bible_verses AS v
         WHERE v.chapter_id = OLD.chapter_id
       )
     WHERE c.id = OLD.chapter_id;
  END IF;

  IF TG_OP = 'DELETE' THEN
    RETURN OLD;
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS bible_verses_refresh_chapter_count ON public.bible_verses;
CREATE TRIGGER bible_verses_refresh_chapter_count
AFTER INSERT OR UPDATE OF chapter_id OR DELETE ON public.bible_verses
FOR EACH ROW EXECUTE FUNCTION public.refresh_bible_chapter_verses_count();

-- --------------------------------------------------------------------------
-- RLS: leitura publica somente de conteudo integralmente publicado.
-- Escrita apenas para administradores. service_role ignora RLS no importador.
-- --------------------------------------------------------------------------
ALTER TABLE public.bible_translations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bible_books ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bible_chapters ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bible_verses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bible_imports ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS bible_translations_public_read ON public.bible_translations;
CREATE POLICY bible_translations_public_read ON public.bible_translations
FOR SELECT TO anon, authenticated
USING (is_active = true AND is_published = true);

DROP POLICY IF EXISTS bible_translations_admin_write ON public.bible_translations;
CREATE POLICY bible_translations_admin_write ON public.bible_translations
FOR ALL TO authenticated
USING (public.is_admin_user())
WITH CHECK (public.is_admin_user());

DROP POLICY IF EXISTS bible_books_public_read ON public.bible_books;
CREATE POLICY bible_books_public_read ON public.bible_books
FOR SELECT TO anon, authenticated
USING (
  is_published = true
  AND EXISTS (
    SELECT 1
    FROM public.bible_translations AS t
    WHERE t.id = translation_id
      AND t.is_active = true
      AND t.is_published = true
  )
);

DROP POLICY IF EXISTS bible_books_admin_write ON public.bible_books;
CREATE POLICY bible_books_admin_write ON public.bible_books
FOR ALL TO authenticated
USING (public.is_admin_user())
WITH CHECK (public.is_admin_user());

DROP POLICY IF EXISTS bible_chapters_public_read ON public.bible_chapters;
CREATE POLICY bible_chapters_public_read ON public.bible_chapters
FOR SELECT TO anon, authenticated
USING (
  is_published = true
  AND EXISTS (
    SELECT 1
    FROM public.bible_books AS b
    JOIN public.bible_translations AS t ON t.id = b.translation_id
    WHERE b.id = book_id
      AND b.is_published = true
      AND t.is_active = true
      AND t.is_published = true
  )
);

DROP POLICY IF EXISTS bible_chapters_admin_write ON public.bible_chapters;
CREATE POLICY bible_chapters_admin_write ON public.bible_chapters
FOR ALL TO authenticated
USING (public.is_admin_user())
WITH CHECK (public.is_admin_user());

DROP POLICY IF EXISTS bible_verses_public_read ON public.bible_verses;
CREATE POLICY bible_verses_public_read ON public.bible_verses
FOR SELECT TO anon, authenticated
USING (
  EXISTS (
    SELECT 1
    FROM public.bible_chapters AS c
    JOIN public.bible_books AS b ON b.id = c.book_id
    JOIN public.bible_translations AS t ON t.id = b.translation_id
    WHERE c.id = chapter_id
      AND c.is_published = true
      AND b.is_published = true
      AND t.is_active = true
      AND t.is_published = true
  )
);

DROP POLICY IF EXISTS bible_verses_admin_write ON public.bible_verses;
CREATE POLICY bible_verses_admin_write ON public.bible_verses
FOR ALL TO authenticated
USING (public.is_admin_user())
WITH CHECK (public.is_admin_user());

DROP POLICY IF EXISTS bible_imports_admin_all ON public.bible_imports;
CREATE POLICY bible_imports_admin_all ON public.bible_imports
FOR ALL TO authenticated
USING (public.is_admin_user())
WITH CHECK (public.is_admin_user());

-- --------------------------------------------------------------------------
-- RPC de leitura de capitulo: uma chamada retorna cabecalho e versiculos.
-- --------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.get_bible_chapter(
  p_translation_code text,
  p_book_slug text,
  p_chapter_number integer
)
RETURNS TABLE (
  translation_code text,
  translation_name text,
  book_name text,
  book_slug text,
  book_abbreviation text,
  testament text,
  chapter_number integer,
  chapter_title text,
  chapter_slug text,
  verse_number integer,
  verse_text text,
  is_red_letter boolean,
  paragraph_number integer,
  section_title text,
  source_page integer
)
LANGUAGE sql
STABLE
SECURITY INVOKER
SET search_path = public
AS $$
  SELECT
    t.code::text,
    t.name::text,
    b.name::text,
    b.slug::text,
    b.abbreviation::text,
    b.testament::text,
    c.chapter_number::integer,
    c.title::text,
    c.slug::text,
    v.verse_number::integer,
    v.verse_text,
    v.is_red_letter,
    v.paragraph_number::integer,
    v.section_title::text,
    v.source_page
  FROM public.bible_translations AS t
  JOIN public.bible_books AS b ON b.translation_id = t.id
  JOIN public.bible_chapters AS c ON c.book_id = b.id
  JOIN public.bible_verses AS v ON v.chapter_id = c.id
  WHERE t.code = lower(btrim(p_translation_code))
    AND b.slug = lower(btrim(p_book_slug))
    AND c.chapter_number = p_chapter_number
    AND t.is_active = true
    AND t.is_published = true
    AND b.is_published = true
    AND c.is_published = true
  ORDER BY v.verse_number;
$$;

REVOKE ALL ON FUNCTION public.get_bible_chapter(text, text, integer) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_bible_chapter(text, text, integer) TO anon, authenticated;

-- Busca textual em versiculos publicados.
CREATE OR REPLACE FUNCTION public.search_bible_verses(
  p_query text,
  p_translation_code text DEFAULT 'acf',
  p_limit integer DEFAULT 20
)
RETURNS TABLE (
  book_name text,
  book_slug text,
  chapter_number integer,
  chapter_slug text,
  verse_number integer,
  verse_text text,
  reference text,
  rank real
)
LANGUAGE sql
STABLE
SECURITY INVOKER
SET search_path = public
AS $$
  WITH search_query AS (
    SELECT websearch_to_tsquery('portuguese', btrim(p_query)) AS query
    WHERE length(btrim(p_query)) >= 2
  )
  SELECT
    b.name::text,
    b.slug::text,
    c.chapter_number::integer,
    c.slug::text,
    v.verse_number::integer,
    v.verse_text,
    concat(b.name, ' ', c.chapter_number, ':', v.verse_number)::text,
    ts_rank_cd(v.search_vector, q.query)::real
  FROM search_query AS q
  JOIN public.bible_verses AS v ON v.search_vector @@ q.query
  JOIN public.bible_chapters AS c ON c.id = v.chapter_id
  JOIN public.bible_books AS b ON b.id = c.book_id
  JOIN public.bible_translations AS t ON t.id = b.translation_id
  WHERE t.code = lower(btrim(p_translation_code))
    AND t.is_active = true
    AND t.is_published = true
    AND b.is_published = true
    AND c.is_published = true
  ORDER BY ts_rank_cd(v.search_vector, q.query) DESC, b.canon_order, c.chapter_number, v.verse_number
  LIMIT LEAST(GREATEST(COALESCE(p_limit, 20), 1), 100);
$$;

REVOKE ALL ON FUNCTION public.search_bible_verses(text, text, integer) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.search_bible_verses(text, text, integer) TO anon, authenticated;

-- Relatorio administrativo de integridade antes da publicacao.
CREATE OR REPLACE FUNCTION public.validate_bible_translation(p_translation_code text)
RETURNS jsonb
LANGUAGE sql
STABLE
SECURITY INVOKER
SET search_path = public
AS $$
  WITH selected_translation AS (
    SELECT id FROM public.bible_translations WHERE code = lower(btrim(p_translation_code))
  ),
  counts AS (
    SELECT
      (SELECT count(*) FROM public.bible_books b WHERE b.translation_id IN (SELECT id FROM selected_translation)) AS books_count,
      (SELECT count(*) FROM public.bible_chapters c JOIN public.bible_books b ON b.id = c.book_id WHERE b.translation_id IN (SELECT id FROM selected_translation)) AS chapters_count,
      (SELECT count(*) FROM public.bible_verses v JOIN public.bible_chapters c ON c.id = v.chapter_id JOIN public.bible_books b ON b.id = c.book_id WHERE b.translation_id IN (SELECT id FROM selected_translation)) AS verses_count,
      (SELECT count(*) FROM public.bible_chapters c JOIN public.bible_books b ON b.id = c.book_id WHERE b.translation_id IN (SELECT id FROM selected_translation) AND c.verses_count = 0) AS empty_chapters_count,
      (SELECT count(*) FROM public.bible_books b WHERE b.translation_id IN (SELECT id FROM selected_translation) AND b.chapters_count <> (SELECT count(*) FROM public.bible_chapters c WHERE c.book_id = b.id)) AS books_with_chapter_mismatch
  )
  SELECT jsonb_build_object(
    'translation_code', lower(btrim(p_translation_code)),
    'books', books_count,
    'chapters', chapters_count,
    'verses', verses_count,
    'empty_chapters', empty_chapters_count,
    'books_with_chapter_mismatch', books_with_chapter_mismatch,
    'ready_to_publish', (
      books_count = 66
      AND chapters_count = 1189
      AND verses_count >= 30000
      AND empty_chapters_count = 0
      AND books_with_chapter_mismatch = 0
    )
  )
  FROM counts;
$$;

REVOKE ALL ON FUNCTION public.validate_bible_translation(text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.validate_bible_translation(text) TO authenticated;

-- --------------------------------------------------------------------------
-- Permissoes de tabela. RLS continua sendo a autoridade final.
-- --------------------------------------------------------------------------
GRANT SELECT ON public.bible_translations, public.bible_books, public.bible_chapters, public.bible_verses
TO anon, authenticated;

GRANT INSERT, UPDATE, DELETE ON public.bible_translations, public.bible_books, public.bible_chapters, public.bible_verses, public.bible_imports
TO authenticated;

GRANT SELECT ON public.bible_imports TO authenticated;

GRANT USAGE, SELECT ON SEQUENCE
  public.bible_translations_id_seq,
  public.bible_books_id_seq,
  public.bible_chapters_id_seq,
  public.bible_verses_id_seq,
  public.bible_imports_id_seq
TO authenticated;

-- --------------------------------------------------------------------------
-- Seed da traducao fornecida pelo responsavel editorial do projeto.
-- Permanece nao publicada ate a validacao dos 66 livros.
-- --------------------------------------------------------------------------
INSERT INTO public.bible_translations (
  code,
  name,
  short_name,
  language_code,
  description,
  rights_status,
  rights_basis,
  source_name,
  source_file_name,
  editorial_notes,
  is_active,
  is_published
)
VALUES (
  'acf',
  'Almeida Corrigida Fiel',
  'ACF',
  'pt-BR',
  'Edicao em portugues fornecida para o leitor biblico do projeto.',
  'user_declared_authorized',
  'Versao declarada como construida e autorizada pelo responsavel do projeto.',
  'PDF editorial fornecido pelo responsavel do projeto',
  'bibliaacfalmeidacorrigidafiel-palavrasdejesusemvermelho-150810225647-lva1-app6891.pdf',
  'Publicar somente depois de validar livros, capitulos, versiculos, acentuacao e palavras de Jesus.',
  true,
  false
)
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  short_name = EXCLUDED.short_name,
  language_code = EXCLUDED.language_code,
  rights_status = EXCLUDED.rights_status,
  rights_basis = EXCLUDED.rights_basis,
  source_name = EXCLUDED.source_name,
  source_file_name = EXCLUDED.source_file_name,
  editorial_notes = EXCLUDED.editorial_notes,
  is_active = true,
  updated_at = now();

-- --------------------------------------------------------------------------
-- Seed dos 66 livros e suas contagens canonicas de capitulos.
-- --------------------------------------------------------------------------
WITH acf AS (
  SELECT id FROM public.bible_translations WHERE code = 'acf'
), catalog(canon_order, testament, name, slug, abbreviation, chapters_count) AS (
  VALUES
    (1,  'old', 'Gênesis',         'genesis',          'Gn',  50),
    (2,  'old', 'Êxodo',           'exodo',            'Êx',  40),
    (3,  'old', 'Levítico',        'levitico',         'Lv',  27),
    (4,  'old', 'Números',         'numeros',          'Nm',  36),
    (5,  'old', 'Deuteronômio',    'deuteronomio',     'Dt',  34),
    (6,  'old', 'Josué',           'josue',            'Js',  24),
    (7,  'old', 'Juízes',          'juizes',           'Jz',  21),
    (8,  'old', 'Rute',            'rute',             'Rt',   4),
    (9,  'old', '1 Samuel',        '1-samuel',         '1Sm', 31),
    (10, 'old', '2 Samuel',        '2-samuel',         '2Sm', 24),
    (11, 'old', '1 Reis',          '1-reis',           '1Rs', 22),
    (12, 'old', '2 Reis',          '2-reis',           '2Rs', 25),
    (13, 'old', '1 Crônicas',      '1-cronicas',       '1Cr', 29),
    (14, 'old', '2 Crônicas',      '2-cronicas',       '2Cr', 36),
    (15, 'old', 'Esdras',          'esdras',           'Ed',  10),
    (16, 'old', 'Neemias',         'neemias',          'Ne',  13),
    (17, 'old', 'Ester',           'ester',            'Et',  10),
    (18, 'old', 'Jó',              'jo',               'Jó',  42),
    (19, 'old', 'Salmos',          'salmos',           'Sl', 150),
    (20, 'old', 'Provérbios',      'proverbios',       'Pv',  31),
    (21, 'old', 'Eclesiastes',     'eclesiastes',      'Ec',  12),
    (22, 'old', 'Cantares',        'cantares',         'Ct',   8),
    (23, 'old', 'Isaías',          'isaias',           'Is',  66),
    (24, 'old', 'Jeremias',        'jeremias',         'Jr',  52),
    (25, 'old', 'Lamentações',     'lamentacoes',      'Lm',   5),
    (26, 'old', 'Ezequiel',        'ezequiel',         'Ez',  48),
    (27, 'old', 'Daniel',          'daniel',           'Dn',  12),
    (28, 'old', 'Oséias',          'oseias',           'Os',  14),
    (29, 'old', 'Joel',            'joel',             'Jl',   3),
    (30, 'old', 'Amós',            'amos',             'Am',   9),
    (31, 'old', 'Obadias',         'obadias',          'Ob',   1),
    (32, 'old', 'Jonas',           'jonas',            'Jn',   4),
    (33, 'old', 'Miquéias',        'miqueias',         'Mq',   7),
    (34, 'old', 'Naum',            'naum',             'Na',   3),
    (35, 'old', 'Habacuque',       'habacuque',        'Hc',   3),
    (36, 'old', 'Sofonias',        'sofonias',         'Sf',   3),
    (37, 'old', 'Ageu',            'ageu',             'Ag',   2),
    (38, 'old', 'Zacarias',        'zacarias',         'Zc',  14),
    (39, 'old', 'Malaquias',       'malaquias',        'Ml',   4),
    (40, 'new', 'Mateus',          'mateus',           'Mt',  28),
    (41, 'new', 'Marcos',          'marcos',           'Mc',  16),
    (42, 'new', 'Lucas',           'lucas',            'Lc',  24),
    (43, 'new', 'João',            'joao',             'Jo',  21),
    (44, 'new', 'Atos',            'atos',             'At',  28),
    (45, 'new', 'Romanos',         'romanos',          'Rm',  16),
    (46, 'new', '1 Coríntios',     '1-corintios',      '1Co', 16),
    (47, 'new', '2 Coríntios',     '2-corintios',      '2Co', 13),
    (48, 'new', 'Gálatas',         'galatas',          'Gl',   6),
    (49, 'new', 'Efésios',         'efesios',          'Ef',   6),
    (50, 'new', 'Filipenses',      'filipenses',       'Fp',   4),
    (51, 'new', 'Colossenses',     'colossenses',      'Cl',   4),
    (52, 'new', '1 Tessalonicenses','1-tessalonicenses','1Ts',  5),
    (53, 'new', '2 Tessalonicenses','2-tessalonicenses','2Ts',  3),
    (54, 'new', '1 Timóteo',       '1-timoteo',        '1Tm',  6),
    (55, 'new', '2 Timóteo',       '2-timoteo',        '2Tm',  4),
    (56, 'new', 'Tito',            'tito',             'Tt',   3),
    (57, 'new', 'Filemom',         'filemom',          'Fm',   1),
    (58, 'new', 'Hebreus',         'hebreus',          'Hb',  13),
    (59, 'new', 'Tiago',           'tiago',            'Tg',   5),
    (60, 'new', '1 Pedro',         '1-pedro',          '1Pe',  5),
    (61, 'new', '2 Pedro',         '2-pedro',          '2Pe',  3),
    (62, 'new', '1 João',          '1-joao',           '1Jo',  5),
    (63, 'new', '2 João',          '2-joao',           '2Jo',  1),
    (64, 'new', '3 João',          '3-joao',           '3Jo',  1),
    (65, 'new', 'Judas',           'judas',            'Jd',   1),
    (66, 'new', 'Apocalipse',      'apocalipse',       'Ap',  22)
)
INSERT INTO public.bible_books (
  translation_id,
  canon_order,
  testament,
  name,
  slug,
  abbreviation,
  chapters_count,
  is_published
)
SELECT
  acf.id,
  catalog.canon_order,
  catalog.testament,
  catalog.name,
  catalog.slug,
  catalog.abbreviation,
  catalog.chapters_count,
  false
FROM acf CROSS JOIN catalog
ON CONFLICT (translation_id, canon_order) DO UPDATE SET
  testament = EXCLUDED.testament,
  name = EXCLUDED.name,
  slug = EXCLUDED.slug,
  abbreviation = EXCLUDED.abbreviation,
  chapters_count = EXCLUDED.chapters_count,
  updated_at = now();

-- Cria os 1.189 capitulos vazios. Titulos e slugs descritivos entram no import.
INSERT INTO public.bible_chapters (
  book_id,
  chapter_number,
  slug,
  is_published
)
SELECT
  b.id,
  chapter_number::smallint,
  chapter_number::text,
  false
FROM public.bible_books AS b
JOIN public.bible_translations AS t ON t.id = b.translation_id AND t.code = 'acf'
CROSS JOIN LATERAL generate_series(1, b.chapters_count::integer) AS chapter_number
ON CONFLICT (book_id, chapter_number) DO NOTHING;

COMMIT;

-- Verificacao esperada logo apos executar esta migracao:
-- SELECT public.validate_bible_translation('acf');
-- Resultado inicial: 66 livros, 1.189 capitulos, 0 versiculos, 1.189 vazios.
