-- Referencias cruzadas da Biblia: dados factuais separados do texto da traducao.
-- Fonte prevista para a primeira carga: OpenBible.info, CC BY 2016.
-- Execute este arquivo no SQL Editor antes de usar o importador correspondente.

BEGIN;

CREATE TABLE IF NOT EXISTS public.bible_cross_references (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  translation_code varchar(24) NOT NULL DEFAULT 'acf',
  source_book_slug varchar(120) NOT NULL,
  source_chapter smallint NOT NULL CHECK (source_chapter BETWEEN 1 AND 150),
  source_verse smallint NOT NULL CHECK (source_verse BETWEEN 1 AND 200),
  target_book_slug varchar(120) NOT NULL,
  target_chapter smallint NOT NULL CHECK (target_chapter BETWEEN 1 AND 150),
  target_verse smallint NOT NULL CHECK (target_verse BETWEEN 1 AND 200),
  vote_count integer NOT NULL DEFAULT 0 CHECK (vote_count >= 0),
  source_name text NOT NULL DEFAULT 'OpenBible.info',
  source_url text NOT NULL DEFAULT 'https://www.openbible.info/labs/cross-references/',
  license_name text NOT NULL DEFAULT 'CC BY 2016',
  imported_at timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT bible_cross_references_unique UNIQUE (
    translation_code, source_book_slug, source_chapter, source_verse,
    target_book_slug, target_chapter, target_verse
  )
);

CREATE INDEX IF NOT EXISTS bible_cross_references_source_idx
  ON public.bible_cross_references (translation_code, source_book_slug, source_chapter, source_verse, vote_count DESC);

ALTER TABLE public.bible_cross_references ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Leitura publica de referencias cruzadas" ON public.bible_cross_references;
CREATE POLICY "Leitura publica de referencias cruzadas"
  ON public.bible_cross_references FOR SELECT
  USING (true);

CREATE OR REPLACE FUNCTION public.get_bible_cross_references(
  p_translation_code text,
  p_book_slug text,
  p_chapter_number smallint,
  p_max_per_verse integer DEFAULT 3
)
RETURNS TABLE (
  source_verse smallint,
  target_book_slug varchar,
  target_chapter smallint,
  target_verse smallint,
  vote_count integer
)
LANGUAGE sql
STABLE
SECURITY INVOKER
SET search_path = public
AS $$
  SELECT ranked.source_verse,
         ranked.target_book_slug,
         ranked.target_chapter,
         ranked.target_verse,
         ranked.vote_count
  FROM (
    SELECT reference.source_verse,
           reference.target_book_slug,
           reference.target_chapter,
           reference.target_verse,
           reference.vote_count,
           row_number() OVER (
             PARTITION BY reference.source_verse
             ORDER BY reference.vote_count DESC,
                      reference.target_book_slug,
                      reference.target_chapter,
                      reference.target_verse
           ) AS position
    FROM public.bible_cross_references AS reference
    WHERE reference.translation_code = lower(p_translation_code)
      AND reference.source_book_slug = p_book_slug
      AND reference.source_chapter = p_chapter_number
  ) AS ranked
  WHERE ranked.position <= GREATEST(1, LEAST(COALESCE(p_max_per_verse, 3), 6))
  ORDER BY ranked.source_verse, ranked.position;
$$;

GRANT EXECUTE ON FUNCTION public.get_bible_cross_references(text, text, smallint, integer) TO anon, authenticated;

COMMENT ON TABLE public.bible_cross_references IS
  'Referencias cruzadas factuais. Primeira fonte: OpenBible.info, CC BY 2016.';

COMMIT;
