-- ============================================================================
-- MODULO: Biblia em Audio por capitulo
-- Execute este arquivo no SQL Editor do Supabase apos CREATE_BIBLE_TEXT_MODULE.
-- Cada capitulo pode possuir um unico video do YouTube, reproduzido como audio.
-- ============================================================================

BEGIN;

CREATE TABLE IF NOT EXISTS public.bible_chapter_audio (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  chapter_id bigint NOT NULL REFERENCES public.bible_chapters(id) ON DELETE CASCADE,
  youtube_video_id varchar(32) NOT NULL,
  youtube_url text NOT NULL,
  title varchar(220),
  thumbnail_url text,
  duration_seconds integer,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT bible_chapter_audio_one_per_chapter UNIQUE (chapter_id),
  CONSTRAINT bible_chapter_audio_video_id_format CHECK (youtube_video_id ~ '^[A-Za-z0-9_-]{6,32}$'),
  CONSTRAINT bible_chapter_audio_duration_check CHECK (duration_seconds IS NULL OR duration_seconds >= 0)
);

COMMENT ON TABLE public.bible_chapter_audio IS
  'Videos do YouTube vinculados a capitulos para a experiencia Biblia em Audio.';

CREATE INDEX IF NOT EXISTS bible_chapter_audio_active_idx
  ON public.bible_chapter_audio (chapter_id, is_active);

DROP TRIGGER IF EXISTS bible_chapter_audio_set_updated_at ON public.bible_chapter_audio;
CREATE TRIGGER bible_chapter_audio_set_updated_at
BEFORE UPDATE ON public.bible_chapter_audio
FOR EACH ROW EXECUTE FUNCTION public.set_bible_updated_at();

ALTER TABLE public.bible_chapter_audio ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS bible_chapter_audio_public_read ON public.bible_chapter_audio;
CREATE POLICY bible_chapter_audio_public_read ON public.bible_chapter_audio
FOR SELECT TO anon, authenticated
USING (
  is_active = true
  AND EXISTS (
    SELECT 1 FROM public.bible_chapters c
    JOIN public.bible_books b ON b.id = c.book_id
    JOIN public.bible_translations t ON t.id = b.translation_id
    WHERE c.id = chapter_id
      AND c.is_published = true
      AND b.is_published = true
      AND t.is_active = true
      AND t.is_published = true
  )
);

DROP POLICY IF EXISTS bible_chapter_audio_admin_write ON public.bible_chapter_audio;
CREATE POLICY bible_chapter_audio_admin_write ON public.bible_chapter_audio
FOR ALL TO authenticated
USING (public.is_admin_user())
WITH CHECK (public.is_admin_user());

GRANT SELECT ON public.bible_chapter_audio TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE ON public.bible_chapter_audio TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.bible_chapter_audio_id_seq TO authenticated;

CREATE OR REPLACE FUNCTION public.get_bible_chapter_audio(
  p_translation_code text,
  p_book_slug text,
  p_chapter_number integer
)
RETURNS TABLE (
  id bigint,
  youtube_video_id text,
  youtube_url text,
  title text,
  thumbnail_url text,
  duration_seconds integer
)
LANGUAGE sql
STABLE
SECURITY INVOKER
SET search_path = public
AS $$
  SELECT a.id, a.youtube_video_id::text, a.youtube_url, a.title::text,
         a.thumbnail_url, a.duration_seconds
  FROM public.bible_chapter_audio a
  JOIN public.bible_chapters c ON c.id = a.chapter_id
  JOIN public.bible_books b ON b.id = c.book_id
  JOIN public.bible_translations t ON t.id = b.translation_id
  WHERE t.code = lower(btrim(p_translation_code))
    AND b.slug = lower(btrim(p_book_slug))
    AND c.chapter_number = p_chapter_number
    AND a.is_active = true
    AND c.is_published = true
    AND b.is_published = true
    AND t.is_active = true
    AND t.is_published = true
  LIMIT 1;
$$;

REVOKE ALL ON FUNCTION public.get_bible_chapter_audio(text, text, integer) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_bible_chapter_audio(text, text, integer) TO anon, authenticated;

COMMIT;
