-- ============================================
-- FIX: Trigger de criação automática de usuário
-- Execute no SQL Editor do Supabase
-- ============================================

-- 1. Primeiro, vamos verificar se existe algum trigger na tabela auth.users
-- Execute esta query primeiro para ver os triggers existentes:
SELECT trigger_name, event_manipulation, action_statement 
FROM information_schema.triggers 
WHERE event_object_table = 'users' 
AND event_object_schema = 'auth';

-- 2. Se houver um trigger chamado "on_auth_user_created" ou similar,
-- ele pode estar tentando inserir na tabela usuarios e falhando.
-- Vamos verificar a função associada:
SELECT proname, prosrc 
FROM pg_proc 
WHERE proname LIKE '%user%' OR proname LIKE '%usuario%';

-- 3. SOLUÇÃO: Criar ou substituir a função de trigger correta
-- Esta função cria automaticamente um registro na tabela usuarios
-- quando um novo usuário se registra via Supabase Auth

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.usuarios (auth_id, nome, email, tipo, ativo, plano, created_at)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data->>'nome', NEW.raw_user_meta_data->>'full_name', split_part(NEW.email, '@', 1)),
    NEW.email,
    'usuario',
    true,
    'free',
    NOW()
  )
  ON CONFLICT (auth_id) DO UPDATE SET
    email = EXCLUDED.email,
    nome = COALESCE(EXCLUDED.nome, usuarios.nome);
  RETURN NEW;
EXCEPTION WHEN OTHERS THEN
  -- Se der erro, não bloquear o registro do usuário
  RAISE WARNING 'Erro ao criar usuario: %', SQLERRM;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 4. Verificar se o trigger já existe e removê-lo se necessário
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;

-- 5. Criar o trigger
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_new_user();

-- 6. Garantir que a função tenha permissão para executar
GRANT EXECUTE ON FUNCTION public.handle_new_user() TO service_role;
GRANT EXECUTE ON FUNCTION public.handle_new_user() TO authenticated;

-- 7. Verificar a estrutura da tabela usuarios para garantir que está correta
-- A tabela DEVE ter estas colunas:
SELECT column_name, data_type, is_nullable, column_default
FROM information_schema.columns
WHERE table_name = 'usuarios' AND table_schema = 'public'
ORDER BY ordinal_position;

-- 8. Se a tabela não existir, criar:
CREATE TABLE IF NOT EXISTS public.usuarios (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  auth_id UUID UNIQUE,
  nome VARCHAR(255) NOT NULL DEFAULT '',
  email VARCHAR(255) NOT NULL UNIQUE,
  avatar_url TEXT,
  tipo VARCHAR(20) DEFAULT 'usuario',
  ativo BOOLEAN DEFAULT true,
  plano VARCHAR(20) DEFAULT 'free',
  telefone VARCHAR(20),
  localizacao VARCHAR(255),
  data_nascimento DATE,
  biografia TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 9. Adicionar e corrigir coluna auth_id e ativo se não existir
DO $$
BEGIN
  -- Adicionar auth_id se não existir
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'usuarios' AND column_name = 'auth_id' AND table_schema = 'public'
  ) THEN
    ALTER TABLE public.usuarios ADD COLUMN auth_id UUID UNIQUE;
  END IF;
  
  -- Corrigir coluna ativo se for integer
  IF EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'usuarios' 
    AND column_name = 'ativo' 
    AND table_schema = 'public'
    AND data_type = 'integer'
  ) THEN
    -- Remover default primeiro
    ALTER TABLE public.usuarios ALTER COLUMN ativo DROP DEFAULT;
    -- Converter tipo
    ALTER TABLE public.usuarios ALTER COLUMN ativo TYPE BOOLEAN USING (ativo = 1);
    -- Adicionar novo default
    ALTER TABLE public.usuarios ALTER COLUMN ativo SET DEFAULT true;
    RAISE NOTICE 'Coluna ativo convertida para BOOLEAN na tabela public.usuarios';
  END IF;
END $$;

-- 10. Habilitar RLS e criar políticas
ALTER TABLE public.usuarios ENABLE ROW LEVEL SECURITY;

-- Remover políticas antigas
DROP POLICY IF EXISTS "Permitir leitura pública" ON public.usuarios;
DROP POLICY IF EXISTS "Permitir insert via trigger" ON public.usuarios;
DROP POLICY IF EXISTS "Permitir update próprio" ON public.usuarios;

-- Criar novas políticas
CREATE POLICY "Permitir leitura pública" ON public.usuarios
  FOR SELECT USING (true);

CREATE POLICY "Permitir insert via trigger" ON public.usuarios
  FOR INSERT WITH CHECK (true);

CREATE POLICY "Permitir update próprio" ON public.usuarios
  FOR UPDATE USING (auth.uid() = auth_id);

-- 11. Verificar resultado
SELECT 'Configuração concluída!' AS status;
