-- ============================================
-- FIX: Estrutura da tabela usuarios para Supabase Auth
-- Execute este script no SQL Editor do Supabase
-- ============================================

-- 1. Verificar se a tabela usuarios existe e criar se não existir
CREATE TABLE IF NOT EXISTS usuarios (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  auth_id UUID UNIQUE,
  nome VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  avatar_url TEXT,
  tipo VARCHAR(20) DEFAULT 'usuario' CHECK (tipo IN ('usuario', 'compositor', 'admin')),
  ativo BOOLEAN DEFAULT true,
  plano VARCHAR(20) DEFAULT 'free' CHECK (plano IN ('free', 'premium')),
  telefone VARCHAR(20),
  localizacao VARCHAR(255),
  data_nascimento DATE,
  biografia TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Adicionar coluna auth_id se não existir
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'usuarios' AND column_name = 'auth_id'
  ) THEN
    ALTER TABLE usuarios ADD COLUMN auth_id UUID UNIQUE;
  END IF;
END $$;

-- 3. Adicionar coluna plano se não existir
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'usuarios' AND column_name = 'plano'
  ) THEN
    ALTER TABLE usuarios ADD COLUMN plano VARCHAR(20) DEFAULT 'free';
  END IF;
END $$;

-- 3.1 Converter coluna ativo de INTEGER para BOOLEAN se necessário
DO $$
BEGIN
  -- Se a coluna ativo for do tipo integer, converter para boolean
  IF EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'usuarios' 
    AND column_name = 'ativo' 
    AND data_type = 'integer'
  ) THEN
    ALTER TABLE usuarios ALTER COLUMN ativo TYPE BOOLEAN USING (ativo = 1);
    ALTER TABLE usuarios ALTER COLUMN ativo SET DEFAULT true;
  END IF;
END $$;

-- 4. Habilitar Row Level Security
ALTER TABLE usuarios ENABLE ROW LEVEL SECURITY;

-- 5. Remover políticas existentes (para evitar conflitos)
DROP POLICY IF EXISTS "Permitir leitura pública de usuarios" ON usuarios;
DROP POLICY IF EXISTS "Permitir registro de novos usuarios" ON usuarios;
DROP POLICY IF EXISTS "Permitir update do próprio perfil" ON usuarios;
DROP POLICY IF EXISTS "Permitir select para usuarios autenticados" ON usuarios;
DROP POLICY IF EXISTS "Permitir insert durante registro" ON usuarios;

-- 6. Criar políticas RLS corretas

-- 6.1 Permitir SELECT para qualquer pessoa (leitura pública de perfis)
CREATE POLICY "Permitir leitura pública de usuarios"
ON usuarios FOR SELECT
TO public
USING (true);

-- 6.2 Permitir INSERT durante o registro (usuário já autenticado no Auth)
CREATE POLICY "Permitir registro de novos usuarios"
ON usuarios FOR INSERT
TO authenticated
WITH CHECK (auth.uid()::text = auth_id::text);

-- 6.3 Permitir UPDATE do próprio perfil
CREATE POLICY "Permitir update do próprio perfil"
ON usuarios FOR UPDATE
TO authenticated
USING (auth.uid()::text = auth_id::text)
WITH CHECK (auth.uid()::text = auth_id::text);

-- 7. Criar índices para performance
CREATE INDEX IF NOT EXISTS idx_usuarios_auth_id ON usuarios(auth_id);
CREATE INDEX IF NOT EXISTS idx_usuarios_email ON usuarios(email);
CREATE INDEX IF NOT EXISTS idx_usuarios_tipo ON usuarios(tipo);

-- 8. Criar função para atualizar updated_at automaticamente
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 9. Criar trigger para atualizar updated_at
DROP TRIGGER IF EXISTS update_usuarios_updated_at ON usuarios;
CREATE TRIGGER update_usuarios_updated_at
    BEFORE UPDATE ON usuarios
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- ============================================
-- VERIFICAÇÃO
-- ============================================
SELECT 
  column_name, 
  data_type, 
  is_nullable,
  column_default
FROM information_schema.columns 
WHERE table_name = 'usuarios'
ORDER BY ordinal_position;

-- Verificar políticas RLS
SELECT 
  policyname,
  cmd,
  permissive,
  qual,
  with_check
FROM pg_policies 
WHERE tablename = 'usuarios';
