-- ============================================
-- FIX COMPLETO: Remover trigger problemático
-- Execute PARTE POR PARTE no SQL Editor do Supabase
-- ============================================

-- =============================================
-- PARTE 1: REMOVER TODOS OS TRIGGERS EXISTENTES
-- Execute esta parte primeiro e verifique o resultado
-- =============================================

-- 1.1 Listar todos os triggers na tabela auth.users
SELECT 
    tgname AS trigger_name,
    proname AS function_name
FROM pg_trigger t
JOIN pg_proc p ON t.tgfoid = p.oid
JOIN pg_class c ON t.tgrelid = c.oid
WHERE c.relname = 'users' AND c.relnamespace = (SELECT oid FROM pg_namespace WHERE nspname = 'auth');

-- 1.2 Remover triggers conhecidos (execute um por vez)
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
DROP TRIGGER IF EXISTS handle_new_user ON auth.users;
DROP TRIGGER IF EXISTS create_profile_trigger ON auth.users;
DROP TRIGGER IF EXISTS tr_insert_user ON auth.users;

-- 1.3 Remover funções de trigger antigas
DROP FUNCTION IF EXISTS public.handle_new_user() CASCADE;
DROP FUNCTION IF EXISTS public.create_profile_for_user() CASCADE;
DROP FUNCTION IF EXISTS public.on_auth_user_created() CASCADE;

-- =============================================
-- PARTE 2: VERIFICAR ESTRUTURA DA TABELA USUARIOS
-- Execute e verifique se a tabela existe e está correta
-- =============================================

-- 2.1 Verificar se a tabela existe
SELECT EXISTS (
   SELECT FROM information_schema.tables 
   WHERE table_schema = 'public' AND table_name = 'usuarios'
);

-- 2.2 Ver estrutura atual
SELECT column_name, data_type, is_nullable, column_default
FROM information_schema.columns
WHERE table_schema = 'public' AND table_name = 'usuarios'
ORDER BY ordinal_position;

-- =============================================
-- PARTE 3: RECRIAR TABELA (SE NECESSÁRIO)
-- Execute APENAS se a tabela não existir ou estiver errada
-- =============================================

-- 3.1 Dropar e recriar tabela (CUIDADO: remove todos os dados!)
-- DESCOMENTE APENAS SE QUISER RECRIAR A TABELA DO ZERO
/*
DROP TABLE IF EXISTS public.usuarios CASCADE;

CREATE TABLE public.usuarios (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  auth_id UUID UNIQUE,
  nome TEXT NOT NULL DEFAULT '',
  email TEXT UNIQUE,
  avatar_url TEXT,
  tipo TEXT DEFAULT 'usuario',
  ativo BOOLEAN DEFAULT true,
  plano TEXT DEFAULT 'free',
  telefone TEXT,
  localizacao TEXT,
  data_nascimento DATE,
  biografia TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
*/

-- 3.2 OU adicionar apenas as colunas que faltam
ALTER TABLE public.usuarios ADD COLUMN IF NOT EXISTS auth_id UUID;
ALTER TABLE public.usuarios ADD COLUMN IF NOT EXISTS plano TEXT DEFAULT 'free';

-- 3.3 Criar índice único para auth_id se não existir
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_indexes WHERE indexname = 'usuarios_auth_id_key'
  ) THEN
    CREATE UNIQUE INDEX usuarios_auth_id_key ON public.usuarios(auth_id);
  END IF;
END $$;

-- =============================================
-- PARTE 4: CONFIGURAR RLS SEM TRIGGER
-- Execute para permitir inserções
-- =============================================

-- 4.1 Desabilitar RLS temporariamente para permitir inserções
ALTER TABLE public.usuarios DISABLE ROW LEVEL SECURITY;

-- 4.2 OU habilitar RLS com políticas permissivas
-- ALTER TABLE public.usuarios ENABLE ROW LEVEL SECURITY;
-- DROP POLICY IF EXISTS "allow_all" ON public.usuarios;
-- CREATE POLICY "allow_all" ON public.usuarios FOR ALL USING (true) WITH CHECK (true);

-- =============================================
-- PARTE 5: VERIFICAÇÃO FINAL
-- Execute para confirmar que está tudo certo
-- =============================================

-- 5.1 Verificar triggers (deve retornar vazio)
SELECT tgname AS trigger_name
FROM pg_trigger t
JOIN pg_class c ON t.tgrelid = c.oid
WHERE c.relname = 'users' AND c.relnamespace = (SELECT oid FROM pg_namespace WHERE nspname = 'auth')
AND NOT tgisinternal;

-- 5.2 Verificar estrutura da tabela
SELECT column_name, data_type FROM information_schema.columns
WHERE table_name = 'usuarios' AND table_schema = 'public';

-- 5.3 Verificar RLS
SELECT relname, relrowsecurity FROM pg_class WHERE relname = 'usuarios';

SELECT 'Configuração concluída! Tente registrar novamente.' AS status;
