-- ============================================
-- FIX: Tabela favoritos para Supabase
-- Execute este script no SQL Editor do Supabase
-- ============================================

-- 1. Verificar se a tabela favoritos existe e criar se não existir
CREATE TABLE IF NOT EXISTS favoritos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id BIGINT NOT NULL,
  hino_id BIGINT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  
  -- Constraint para evitar duplicatas
  CONSTRAINT unique_favorito UNIQUE (usuario_id, hino_id)
);

-- 3. Verificar e corrigir tipo da coluna ativo na tabela usuarios
DO $$
BEGIN
  -- Verificar se a coluna ativo existe e seu tipo
  IF EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'usuarios' 
    AND column_name = 'ativo'
  ) THEN
    -- Se for integer, converter para boolean
    IF EXISTS (
      SELECT 1 FROM information_schema.columns 
      WHERE table_name = 'usuarios' 
      AND column_name = 'ativo' 
      AND data_type = 'integer'
    ) THEN
      -- Primeiro remover o default se existir
      ALTER TABLE usuarios ALTER COLUMN ativo DROP DEFAULT;
      -- Depois converter o tipo
      ALTER TABLE usuarios ALTER COLUMN ativo TYPE BOOLEAN USING (ativo = 1);
      -- Por fim, adicionar o novo default
      ALTER TABLE usuarios ALTER COLUMN ativo SET DEFAULT true;
      RAISE NOTICE 'Coluna ativo convertida de INTEGER para BOOLEAN';
    END IF;
  ELSE
    -- Se não existir, criar como boolean
    ALTER TABLE usuarios ADD COLUMN ativo BOOLEAN DEFAULT true;
    RAISE NOTICE 'Coluna ativo criada como BOOLEAN';
  END IF;
END $$;

-- 4. Habilitar Row Level Security
ALTER TABLE favoritos ENABLE ROW LEVEL SECURITY;

-- 3. Remover políticas existentes (para evitar conflitos)
DROP POLICY IF EXISTS "Permitir leitura dos próprios favoritos" ON favoritos;
DROP POLICY IF EXISTS "Permitir inserção de favoritos" ON favoritos;
DROP POLICY IF EXISTS "Permitir remoção dos próprios favoritos" ON favoritos;

-- 4. Criar políticas RLS corretas

-- 4.1 Permitir SELECT dos próprios favoritos
CREATE POLICY "Permitir leitura dos próprios favoritos"
ON favoritos FOR SELECT
TO authenticated
USING (auth.uid()::text IN (
  SELECT auth_id::text FROM usuarios WHERE id = usuario_id AND ativo = true
));

-- 4.2 Permitir INSERT de favoritos
CREATE POLICY "Permitir inserção de favoritos"
ON favoritos FOR INSERT
TO authenticated
WITH CHECK (auth.uid()::text IN (
  SELECT auth_id::text FROM usuarios WHERE id = usuario_id AND ativo = true
));

-- 4.3 Permitir DELETE dos próprios favoritos
CREATE POLICY "Permitir remoção dos próprios favoritos"
ON favoritos FOR DELETE
TO authenticated
USING (auth.uid()::text IN (
  SELECT auth_id::text FROM usuarios WHERE id = usuario_id AND ativo = true
));

-- 5. Criar índices para performance
CREATE INDEX IF NOT EXISTS idx_favoritos_usuario_id ON favoritos(usuario_id);
CREATE INDEX IF NOT EXISTS idx_favoritos_hino_id ON favoritos(hino_id);
CREATE INDEX IF NOT EXISTS idx_favoritos_created_at ON favoritos(created_at DESC);

-- 6. Garantir que a tabela hinos exista com as colunas necessárias
CREATE TABLE IF NOT EXISTS hinos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  numero INTEGER,
  titulo VARCHAR(255) NOT NULL,
  compositor VARCHAR(255),
  categoria VARCHAR(100),
  audio_url TEXT,
  cover_url TEXT,
  duracao VARCHAR(20),
  letra TEXT,
  tags TEXT,
  ativo INTEGER DEFAULT 1,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. Habilitar RLS na tabela hinos (se ainda não estiver)
ALTER TABLE hinos ENABLE ROW LEVEL SECURITY;

-- 8. Política para leitura pública de hinos
DROP POLICY IF EXISTS "Permitir leitura pública de hinos" ON hinos;
CREATE POLICY "Permitir leitura pública de hinos"
ON hinos FOR SELECT
TO public
USING (ativo = 1);

-- 9. Criar índices para hinos
CREATE INDEX IF NOT EXISTS idx_hinos_titulo ON hinos(titulo);
CREATE INDEX IF NOT EXISTS idx_hinos_compositor ON hinos(compositor);
CREATE INDEX IF NOT EXISTS idx_hinos_categoria ON hinos(categoria);
CREATE INDEX IF NOT EXISTS idx_hinos_ativo ON hinos(ativo);

-- ============================================
-- VERIFICAÇÃO
-- ============================================

-- Verificar estrutura da tabela favoritos
SELECT 
  column_name, 
  data_type, 
  is_nullable,
  column_default
FROM information_schema.columns 
WHERE table_name = 'favoritos'
ORDER BY ordinal_position;

-- Verificar políticas RLS da tabela favoritos
SELECT 
  policyname,
  cmd,
  permissive,
  qual,
  with_check
FROM pg_policies 
WHERE tablename = 'favoritos';

-- Verificar se há dados na tabela
SELECT COUNT(*) as total_favoritos FROM favoritos;

-- Testar consulta usada no frontend (substitua USER_ID pelo ID real)
-- SELECT
--   favoritos.id,
--   favoritos.created_at,
--   hinos.id,
--   hinos.titulo,
--   hinos.compositor,
--   hinos.duracao,
--   hinos.cover_url
-- FROM favoritos
-- LEFT JOIN hinos ON favoritos.hino_id = hinos.id
-- WHERE favoritos.usuario_id = USER_ID
-- ORDER BY favoritos.created_at DESC
-- LIMIT 5;
