// STUB temporário - Substituir com implementação real quando backend estiver pronto
export type SiteSettings = {
  site_name?: string;
  site_description?: string;
  contact_email?: string;
  contact_phone?: string;
  social_facebook?: string;
  social_instagram?: string;
  social_youtube?: string;
  social_twitter?: string;
  terms_of_use?: string;
  privacy_policy?: string;
  about_us?: string;
};
export type UpdateSettingsData = Partial<SiteSettings>;

export const getAll = async (..._args: any[]) => [];
export const getById = async (..._args: any[]) => null;
export const create = async (..._args: any[]) => ({ success: true });
export const update = async (..._args: any[]) => ({ success: true });
export const deleteItem = async (..._args: any[]) => ({ success: true });
export const getSiteSettings = async (..._args: any[]): Promise<SiteSettings> => ({});
export const updateSiteSettings = async (..._args: any[]) => ({ success: true });
export const getComments = async (..._args: any[]) => [];
export const deleteComment = async (..._args: any[]) => ({ success: true });
export const approveComment = async (..._args: any[]) => ({ success: true });
export const getClaims = async (..._args: any[]) => [];
export const getCopyrightClaims = async (..._args: any[]) => [];
export const updateClaim = async (..._args: any[]) => ({ success: true });
export const getRoyalties = async (..._args: any[]) => [];
export const processPayment = async (..._args: any[]) => ({ success: true });
export const getAllPlaylists = async (..._args: any[]) => [];
export const createPlaylist = async (..._args: any[]) => ({ success: true });
export const updatePlaylist = async (..._args: any[]) => ({ success: true });
export const deletePlaylist = async (..._args: any[]) => ({ success: true });
export type Comment = any;
export type Claim = any;
export type CopyrightClaim = any;
export type Royalty = any;
export type Playlist = any;
