import React, { useEffect, useState } from 'react';
import { Check, Eye, RefreshCw, X } from 'lucide-react';
import { listCifraContributionsForReview, moderateCifraContribution, type CifraContribution } from '@/lib/cifraContributionsApi';

const AdminCifraContributions: React.FC = () => {
  const [rows, setRows] = useState<CifraContribution[]>([]);
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState<string | null>(null);
  const [notes, setNotes] = useState<Record<string, string>>({});
  const load = async () => { setLoading(true); try { setRows(await listCifraContributionsForReview()); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const decide = async (id: string, decision: 'approved' | 'rejected' | 'changes_requested') => { setBusy(id); try { await moderateCifraContribution(id, decision, notes[id]); await load(); } finally { setBusy(null); } };
  return <main className="mx-auto max-w-6xl px-4 py-8 pb-24"><div className="flex items-center justify-between gap-4"><div><h1 className="text-3xl font-bold text-white">Contribuições de cifras</h1><p className="mt-2 text-gray-400">Revise correções e novas tonalidades antes da publicação.</p></div><button onClick={() => void load()} className="rounded-xl border border-white/10 p-3 text-gray-300 hover:text-white" aria-label="Atualizar"><RefreshCw className={`h-5 w-5 ${loading ? 'animate-spin' : ''}`} /></button></div>{loading ? <p className="mt-10 text-gray-400">A carregar contribuições…</p> : rows.length === 0 ? <p className="mt-10 rounded-2xl border border-white/10 p-6 text-gray-400">Não existem contribuições pendentes.</p> : <div className="mt-8 space-y-4">{rows.map(row => <article key={row.id} className="rounded-2xl border border-white/10 bg-white/[0.03] p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="text-lg font-semibold text-white">{row.title}</h2><p className="mt-1 text-sm text-gray-400">{row.song?.title || row.song_id} · {row.instrument} · Tom {row.original_key}</p><p className="mt-1 text-sm text-gray-500">Contribuição de {row.contributor?.name || row.contributor_id}</p></div><span className="rounded-full bg-amber-400/10 px-3 py-1 text-xs text-amber-200">{row.status}</span></div><textarea value={notes[row.id] || ''} onChange={e => setNotes(current => ({ ...current, [row.id]: e.target.value }))} placeholder="Nota para o contribuidor" className="mt-4 min-h-20 w-full rounded-xl border border-white/10 bg-black/20 p-3 text-sm text-white" /><div className="mt-4 flex flex-wrap gap-2"><button disabled={busy === row.id} onClick={() => void decide(row.id, 'approved')} className="inline-flex items-center gap-2 rounded-xl bg-primary-500 px-4 py-2 font-semibold text-black"><Check className="h-4 w-4" /> Aprovar e publicar</button><button disabled={busy === row.id} onClick={() => void decide(row.id, 'changes_requested')} className="inline-flex items-center gap-2 rounded-xl border border-amber-400/30 px-4 py-2 text-amber-200"><Eye className="h-4 w-4" /> Pedir alterações</button><button disabled={busy === row.id} onClick={() => void decide(row.id, 'rejected')} className="inline-flex items-center gap-2 rounded-xl border border-red-400/30 px-4 py-2 text-red-200"><X className="h-4 w-4" /> Rejeitar</button></div></article>)}</div>}</main>;
};
export default AdminCifraContributions;
