import { lazyWithChunkRecovery } from '@/utils/chunkLoadRecovery';

export const AdminDashboard = lazyWithChunkRecovery(() => import('./AdminDashboard'));
export const AdminApprovals = lazyWithChunkRecovery(() => import('./approvals/AdminApprovals'));

export const AdminUsers = lazyWithChunkRecovery(() => import('./AdminUsers'));
export const AdminUserEdit = lazyWithChunkRecovery(() => import('./AdminUserEdit'));
export const AdminUserForm = lazyWithChunkRecovery(() => import('./AdminUserForm'));

export const AdminComposers = lazyWithChunkRecovery(() => import('./AdminComposers'));
export const AdminComposersPending = lazyWithChunkRecovery(() => import('./AdminComposersPending'));
export const AdminComposersVerified = lazyWithChunkRecovery(() => import('./AdminComposersVerified'));
export const AdminComposerForm = lazyWithChunkRecovery(() => import('./AdminComposerForm'));
export const AdminRoyalties = lazyWithChunkRecovery(() => import('./AdminRoyalties'));

export const AdminHymns = lazyWithChunkRecovery(() => import('./AdminHymns'));
export const AdminHymnForm = lazyWithChunkRecovery(() => import('./AdminHymnForm'));
export const AdminYoutubeImport = lazyWithChunkRecovery(() => import('./AdminYoutubeImport'));
export const AdminSongs = lazyWithChunkRecovery(() => import('./AdminSongs'));
export const AdminSongsPending = lazyWithChunkRecovery(() => import('./songs/AdminSongsPending'));
export const AdminSongDetails = lazyWithChunkRecovery(() => import('./songs/AdminSongDetails'));
export const AdminSongForm = lazyWithChunkRecovery(() => import('./AdminSongForm'));
export const AdminAlbumsPending = lazyWithChunkRecovery(() => import('./AdminAlbumsPending'));
export const AdminAlbums = lazyWithChunkRecovery(() => import('./AdminAlbums'));
export const AdminAlbumForm = lazyWithChunkRecovery(() => import('./AdminAlbumForm'));
export const AdminCategories = lazyWithChunkRecovery(() => import('./AdminCategories'));
export const AdminCategoryForm = lazyWithChunkRecovery(() => import('./AdminCategoryForm'));
export const AdminGenres = lazyWithChunkRecovery(() => import('./AdminGenres'));
export const AdminGenreForm = lazyWithChunkRecovery(() => import('./AdminGenreForm'));
export const AdminTags = lazyWithChunkRecovery(() => import('./AdminTags'));
export const AdminTagForm = lazyWithChunkRecovery(() => import('./AdminTagForm'));
export const AdminPlaylists = lazyWithChunkRecovery(() => import('./playlists/AdminPlaylists'));
export const AdminPlaylistsEditorial = lazyWithChunkRecovery(() => import('./AdminPlaylistsEditorial'));
export const AdminPlaylistForm = lazyWithChunkRecovery(() => import('./AdminPlaylistForm'));

export const AdminBanners = lazyWithChunkRecovery(() => import('./AdminBanners'));
export const AdminBannerForm = lazyWithChunkRecovery(() => import('./AdminBannerForm'));
export const AdminFeatured = lazyWithChunkRecovery(() => import('./AdminFeatured'));
export const AdminFeaturedForm = lazyWithChunkRecovery(() => import('./AdminFeaturedForm'));
export const AdminCollections = lazyWithChunkRecovery(() => import('./AdminCollections'));
export const AdminCollectionForm = lazyWithChunkRecovery(() => import('./AdminCollectionForm'));
export const AdminCampaigns = lazyWithChunkRecovery(() => import('./AdminCampaigns'));
export const AdminCampaignForm = lazyWithChunkRecovery(() => import('./AdminCampaignForm'));
export const AdminPromotions = lazyWithChunkRecovery(() => import('./AdminPromotions'));
export const AdminPromotionForm = lazyWithChunkRecovery(() => import('./AdminPromotionForm'));
export const AdminCoupons = lazyWithChunkRecovery(() => import('./AdminCoupons'));
export const AdminCouponForm = lazyWithChunkRecovery(() => import('./AdminCouponForm'));

export const AdminAnalytics = lazyWithChunkRecovery(() => import('./AdminAnalytics'));
export const AdminReports = lazyWithChunkRecovery(() => import('./reports/AdminReports'));
export const AdminReportDetail = lazyWithChunkRecovery(() => import('./reports/AdminReportDetail'));
export const AdminReportAnalytics = lazyWithChunkRecovery(() => import('./reports/AdminReportAnalytics'));
export const AdminReportLogs = lazyWithChunkRecovery(() => import('./reports/AdminReportLogs'));
export const AdminCustomReports = lazyWithChunkRecovery(() => import('./AdminCustomReports'));
export const AdminLogs = lazyWithChunkRecovery(() => import('./AdminLogs'));
export const AdminLogos = lazyWithChunkRecovery(() => import('./AdminLogos'));
export const AdminComments = lazyWithChunkRecovery(() => import('./AdminComments'));
export const AdminChat = lazyWithChunkRecovery(() => import('./AdminChat'));
export const AdminCopyrightClaims = lazyWithChunkRecovery(() => import('./AdminCopyrightClaims'));

export const AdminSettingsGeneral = lazyWithChunkRecovery(() => import('./AdminSettingsGeneral'));
export const AdminSettingsUsers = lazyWithChunkRecovery(() => import('./AdminSettingsUsers'));
export const AdminSettingsComposers = lazyWithChunkRecovery(() => import('./AdminSettingsComposers'));
export const AdminSettingsEmail = lazyWithChunkRecovery(() => import('./AdminSettingsEmail'));
export const AdminSettingsSecurity = lazyWithChunkRecovery(() => import('./AdminSettingsSecurity'));
export const AdminSettingsIntegrations = lazyWithChunkRecovery(() => import('./AdminSettingsIntegrations'));
export const AdminSEO = lazyWithChunkRecovery(() => import('./AdminSEO'));
export const AdminMenus = lazyWithChunkRecovery(() => import('./AdminMenus'));
export const AdminTheme = lazyWithChunkRecovery(() => import('./AdminTheme'));

export const AdminBackup = lazyWithChunkRecovery(() => import('./AdminBackup'));
export const AdminBackupForm = lazyWithChunkRecovery(() => import('./AdminBackupForm'));
export const AdminImport = lazyWithChunkRecovery(() => import('./AdminImport'));
export const AdminImportForm = lazyWithChunkRecovery(() => import('./AdminImportForm'));
export const AdminArchiveRecovery = lazyWithChunkRecovery(() => import('./AdminArchiveRecovery'));
export const AdminExport = lazyWithChunkRecovery(() => import('./AdminExport'));
export const AdminExportForm = lazyWithChunkRecovery(() => import('./AdminExportForm'));
export const AdminAPI = lazyWithChunkRecovery(() => import('./api/AdminAPI'));
export const AdminAPIForm = lazyWithChunkRecovery(() => import('./AdminAPIForm'));
export const AdminNotices = lazyWithChunkRecovery(() => import('./AdminNotices'));
export const AdminNoticeForm = lazyWithChunkRecovery(() => import('./AdminNoticeForm'));
export const AdminBibleNarrated = lazyWithChunkRecovery(() => import('./AdminBibleNarrated'));
export const AdminBibleNarratedForm = lazyWithChunkRecovery(() => import('./AdminBibleNarratedForm'));
export const AdminBibleAudio = lazyWithChunkRecovery(() => import('./AdminBibleAudio'));
export const AdminCifras = lazyWithChunkRecovery(() => import('./AdminCifras'));
export const AdminCifraForm = lazyWithChunkRecovery(() => import('./AdminCifraForm'));
export const AdminCifraMigrationPage = lazyWithChunkRecovery(() => import('./AdminCifraMigrationPage'));
export const AdminCifraV2Editor = lazyWithChunkRecovery(() => import('./AdminCifraV2Editor'));
export const AdminCifraChordShapes = lazyWithChunkRecovery(() => import('./AdminCifraChordShapes'));
export const AdminCifraReview = lazyWithChunkRecovery(() => import('./AdminCifraReview'));
export const AdminHinario = lazyWithChunkRecovery(() => import('./AdminHinario'));
export const AdminHinarioForm = lazyWithChunkRecovery(() => import('./AdminHinarioForm'));
